### ISSUE TITLE
Use of visualisation library in runner.py

### ISSUE THREAD

**Issue by Alan-Tony** [rilwen/multi-agent-RL-A2C#1]
Hi! I'm trying to understand MA2AC RL algorithm by running this project. I wasn't able to find the visualisation library (used in runner.py) from pip. The closest to it I've found is the one named "visualization" by Berkeley Automation (https://pypi.org/project/visualization/), but it doesn't install correctly on python 3.x

Am I missing something? It would be helpful if you could add the dependencies and the versions of the packages you have used in this project in the README.

Thanks.

**Comment by Daniel-Huff** [comment]
I met problem too. Have you solved it?

**Comment by rilwen** [comment]
I uploaded the missing file. Sorry!
